# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_version '2.221.0'
default_platform :ios

platform :ios do
  before_all do
    setup_ci
  end

  desc 'Builds project and executes unit tests'
  lane :tests do
    run_tests(
        project: "GithubActionsDemo.xcodeproj",
        scheme: "#{ENV['APP_SCHEME_PROD']}"
    )
  end

  desc "Deploy to TestFlight - Production"
  lane :test_flight_prod do
    deploy_to_testflight(env: "prod")
  end

  desc "Deploy to TestFlight - Test Environment"
  lane :test_flight_test do
    deploy_to_testflight(env: "test")
  end

  lane :deploy_to_testflight do |options|
    env = options[:env]
    scheme = env == "prod" ? ENV['APP_SCHEME_PROD'] : ENV['APP_SCHEME_TEST']
    app_identifier = env == "prod" ? ENV['APP_IDENTIFIER_PROD'] : ENV['APP_IDENTIFIER_TEST']

    api_key = app_store_connect_api_key(
      key_id: "#{ENV['APP_STORE_API_PRIVATE_KEY']}",
      issuer_id: "#{ENV['APP_STORE_API_KEY_ISSUER_ID']}",
      key_filepath: "#{ENV['APP_AUTH_KEY_FILEPATH']}",
      duration: "#{ENV['APP_STORE_CONNECT_DURATION']}" 
    )

    previous_build_number = latest_testflight_build_number(
      app_identifier: app_identifier,
      api_key: api_key,
    )
    
    current_build_number = previous_build_number + 1
    increment_build_number(
      xcodeproj: "#{ENV['APP_XCODEPROJ']}",
      build_number: current_build_number
    )

    sync_code_signing(
      type: "appstore",
      readonly: true,
    )

    build_app(
      scheme: scheme,
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates"
    )

    upload_to_testflight(
      app_identifier: app_identifier,
      skip_submission: true,
      skip_waiting_for_build_processing: true
    ) 
  end
end
